/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PersonsIndexRouteImport } from './routes/persons/index'
import { Route as PersonsIdRouteImport } from './routes/persons/$id'
import { Route as PersonsIdIndexRouteImport } from './routes/persons/$id/index'
import { Route as PersonsIdTimelineRouteImport } from './routes/persons/$id/timeline'
import { Route as PersonsIdDatesDateIdRouteImport } from './routes/persons/$id/dates/$dateId'

const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIndexRoute = PersonsIndexRouteImport.update({
  id: '/persons/',
  path: '/persons/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIdRoute = PersonsIdRouteImport.update({
  id: '/persons/$id',
  path: '/persons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIdIndexRoute = PersonsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PersonsIdRoute,
} as any)
const PersonsIdTimelineRoute = PersonsIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => PersonsIdRoute,
} as any)
const PersonsIdDatesDateIdRoute = PersonsIdDatesDateIdRouteImport.update({
  id: '/dates/$dateId',
  path: '/dates/$dateId',
  getParentRoute: () => PersonsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/network': typeof NetworkRoute
  '/persons/$id': typeof PersonsIdRouteWithChildren
  '/persons/': typeof PersonsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/persons/$id/timeline': typeof PersonsIdTimelineRoute
  '/persons/$id/': typeof PersonsIdIndexRoute
  '/persons/$id/dates/$dateId': typeof PersonsIdDatesDateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/network': typeof NetworkRoute
  '/persons': typeof PersonsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tags': typeof TagsIndexRoute
  '/persons/$id/timeline': typeof PersonsIdTimelineRoute
  '/persons/$id': typeof PersonsIdIndexRoute
  '/persons/$id/dates/$dateId': typeof PersonsIdDatesDateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/network': typeof NetworkRoute
  '/persons/$id': typeof PersonsIdRouteWithChildren
  '/persons/': typeof PersonsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/persons/$id/timeline': typeof PersonsIdTimelineRoute
  '/persons/$id/': typeof PersonsIdIndexRoute
  '/persons/$id/dates/$dateId': typeof PersonsIdDatesDateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/network'
    | '/persons/$id'
    | '/persons/'
    | '/settings/'
    | '/tags/'
    | '/persons/$id/timeline'
    | '/persons/$id/'
    | '/persons/$id/dates/$dateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/network'
    | '/persons'
    | '/settings'
    | '/tags'
    | '/persons/$id/timeline'
    | '/persons/$id'
    | '/persons/$id/dates/$dateId'
  id:
    | '__root__'
    | '/'
    | '/network'
    | '/persons/$id'
    | '/persons/'
    | '/settings/'
    | '/tags/'
    | '/persons/$id/timeline'
    | '/persons/$id/'
    | '/persons/$id/dates/$dateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NetworkRoute: typeof NetworkRoute
  PersonsIdRoute: typeof PersonsIdRouteWithChildren
  PersonsIndexRoute: typeof PersonsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/': {
      id: '/persons/'
      path: '/persons'
      fullPath: '/persons/'
      preLoaderRoute: typeof PersonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/$id': {
      id: '/persons/$id'
      path: '/persons/$id'
      fullPath: '/persons/$id'
      preLoaderRoute: typeof PersonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/$id/': {
      id: '/persons/$id/'
      path: '/'
      fullPath: '/persons/$id/'
      preLoaderRoute: typeof PersonsIdIndexRouteImport
      parentRoute: typeof PersonsIdRoute
    }
    '/persons/$id/timeline': {
      id: '/persons/$id/timeline'
      path: '/timeline'
      fullPath: '/persons/$id/timeline'
      preLoaderRoute: typeof PersonsIdTimelineRouteImport
      parentRoute: typeof PersonsIdRoute
    }
    '/persons/$id/dates/$dateId': {
      id: '/persons/$id/dates/$dateId'
      path: '/dates/$dateId'
      fullPath: '/persons/$id/dates/$dateId'
      preLoaderRoute: typeof PersonsIdDatesDateIdRouteImport
      parentRoute: typeof PersonsIdRoute
    }
  }
}

interface PersonsIdRouteChildren {
  PersonsIdTimelineRoute: typeof PersonsIdTimelineRoute
  PersonsIdIndexRoute: typeof PersonsIdIndexRoute
  PersonsIdDatesDateIdRoute: typeof PersonsIdDatesDateIdRoute
}

const PersonsIdRouteChildren: PersonsIdRouteChildren = {
  PersonsIdTimelineRoute: PersonsIdTimelineRoute,
  PersonsIdIndexRoute: PersonsIdIndexRoute,
  PersonsIdDatesDateIdRoute: PersonsIdDatesDateIdRoute,
}

const PersonsIdRouteWithChildren = PersonsIdRoute._addFileChildren(
  PersonsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NetworkRoute: NetworkRoute,
  PersonsIdRoute: PersonsIdRouteWithChildren,
  PersonsIndexRoute: PersonsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
